### ISSUE TITLE
use CPU-GPU-mixed process big dataset error

### ISSUE THREAD

**Issue by looon1** [Starlitnightly/omicverse#651]
## 🐛 Description

I encountered a CUDA out-of-memory error when running a single-cell analysis workflow on a large AnnData object in a Jupyter Notebook environment.

The error appears when GPU acceleration is used, and it may be related to CPU-GPU mixed processing or memory allocation issues.

---

## 🔁 Steps to reproduce

```python
# Load data
adata_all: (1384942, 16248)

%%time
adata_all_filter=ov.pp.qc(adata_all,
              tresh={'mito_perc': 0.2, 'nUMIs': 500, 'detected_genes': 250},
              batch_key='dataset')
adata_all_filter
⚙️ Using CPU/GPU mixed mode for QC...
NVIDIA CUDA GPUs detected:
📊 [CUDA 0] NVIDIA GeForce RTX 3090
    ------------------------------ 12/24576 MiB (0.0%)
📊 [CUDA 1] NVIDIA GeForce RTX 3090
    ------------------------------ 12/24576 MiB (0.0%)

🔍 Quality Control Analysis (CPU-GPU Mixed):
   Dataset shape: 1,384,942 cells × 16,248 genes
   QC mode: seurat
   Doublet detection: scrublet
   Auto-detected mitochondrial prefix: 'MT-'
   Mitochondrial genes: MT-

📊 Step 1: Calculating QC Metrics

   ✓ Gene Family Detection:
   ┌──────────────────────────────┬────────────────────┬────────────────────┐
   │ Gene Family                  │ Genes Found        │ Detection Method   │
   ├──────────────────────────────┼────────────────────┼────────────────────┤
   │ Mitochondrial                │ 13                 │ Auto (MT-)         │
   ├──────────────────────────────┼────────────────────┼────────────────────┤
   │ Ribosomal                    │ 98                 │ Auto (RPS/RPL)     │
   ├──────────────────────────────┼────────────────────┼────────────────────┤
   │ Hemoglobin                   │ 9                  │ Auto (regex)       │
   └──────────────────────────────┴────────────────────┴────────────────────┘

   ✓ QC Metrics Summary:
   ┌─────────────────────────┬────────────────────┬─────────────────────────┐
   │ Metric                  │ Mean               │ Range (Min - Max)       │
   ├─────────────────────────┼────────────────────┼─────────────────────────┤
   │ nUMIs                   │ 4641               │ 205 - 187905            │
   ├─────────────────────────┼────────────────────┼─────────────────────────┤
   │ Detected Genes          │ 1050               │ 17 - 9714               │
   ├─────────────────────────┼────────────────────┼─────────────────────────┤
   │ Mitochondrial %         │ 19.7%              │ 0.0% - 99.6%            │
   ├─────────────────────────┼────────────────────┼─────────────────────────┤
   │ Ribosomal %             │ 18.3%              │ 0.0% - 76.0%            │
   ├─────────────────────────┼────────────────────┼─────────────────────────┤
   │ Hemoglobin %            │ 0.0%               │ 0.0% - 97.5%            │
   └─────────────────────────┴────────────────────┴─────────────────────────┘

🔧 Step 2: Quality Filtering (SEURAT)
   Thresholds: mito≤0.2, nUMIs≥500, genes≥250
   📊 Seurat Filter Results:
     • nUMIs filter (≥500): 26,229 cells failed (1.9%)
     • Genes filter (≥250): 139,788 cells failed (10.1%)
     • Mitochondrial filter (≤0.2): 461,595 cells failed (33.3%)
   ✓ Combined QC filters: 841,910 cells kept (60.8%)

🎯 Step 3: Final Filtering
   Parameters: min_genes=200, min_cells=3
   Ratios: max_genes_ratio=1, max_cells_ratio=1
   ✓ Final filtering: 0 cells, 0 genes removed

🔍 Step 4: Doublet Detection
   ⚠️  Note: 'scrublet' detection is legacy and may not work optimally
   💡 Consider using 'doublets_method=sccomposite' for better results
   🔍 Running scrublet doublet detection...

🔍 Running Scrublet Doublet Detection:
   Mode: cpu-gpu-mixed
   Computing doublet prediction using Scrublet algorithm
   🔍 Filtering genes and cells...
🔍 Filtering genes...
   Parameters: min_cells≥3
   ✓ Filtered: 179 genes removed
🔍 Filtering cells...
   Parameters: min_genes≥3
   ✓ Filtered: 0 cells removed
   🔍 Normalizing data and selecting highly variable genes...

🔍 Count Normalization:
   Target sum: median
   Exclude highly expressed: False

✅ Count Normalization Completed Successfully!
   ✓ Processed: 43,035 cells × 16,069 genes
   ✓ Runtime: 0.14s

🔍 Highly Variable Genes Selection:
   Method: seurat
   ⚠️ Gene indices [6344 6438] fell into a single bin: normalized dispersion set to 1
   💡 Consider decreasing `n_bins` to avoid this effect

✅ HVG Selection Completed Successfully!
   ✓ Selected: 1,307 highly variable genes out of 16,069 total (8.1%)
   ✓ Results added to AnnData object:
     • 'highly_variable': Boolean vector (adata.var)
     • 'means': Float vector (adata.var)
     • 'dispersions': Float vector (adata.var)
     • 'dispersions_norm': Float vector (adata.var)
   🔍 Simulating synthetic doublets...
   🔍 Normalizing observed and simulated data...

🔍 Count Normalization:
   Target sum: 1000000.0
   Exclude highly expressed: False

✅ Count Normalization Completed Successfully!
   ✓ Processed: 43,035 cells × 1,307 genes
   ✓ Runtime: 0.01s

🔍 Count Normalization:
   Target sum: 1000000.0
   Exclude highly expressed: False

✅ Count Normalization Completed Successfully!
   ✓ Processed: 86,070 cells × 1,307 genes
   ✓ Runtime: 0.09s
   🔍 Embedding transcriptomes using PCA...

Using CUDA device: NVIDIA GeForce RTX 3090
✅ Using built-in torch_pca for GPU-accelerated PCA
   🚀 Using torch_pca PCA for CUDA GPU acceleration in scrublet
   🚀 torch_pca PCA backend: CUDA GPU acceleration (scrublet, supports sparse)
   📊 Scrublet PCA input data type - X_obs: ndarray, shape: (43035, 1307), dtype: float64
   📊 Scrublet PCA input data type - X_sim: ndarray, shape: (86070, 1307), dtype: float64
   🔍 Calculating doublet scores...
   🔍 Calling doublets with threshold detection...
   📊 Automatic threshold: 0.783
   📈 Detected doublet rate: 0.0%
   🔍 Detectable doublet fraction: 0.1%
   📊 Overall doublet rate comparison:
     • Expected: 5.0%
     • Estimated: 4.2%
   🔍 Filtering genes and cells...
🔍 Filtering genes...
   Parameters: min_cells≥3
   ✓ Filtered: 18 genes removed
🔍 Filtering cells...
   Parameters: min_genes≥3
   ✓ Filtered: 0 cells removed
   🔍 Normalizing data and selecting highly variable genes...

🔍 Count Normalization:
   Target sum: median
   Exclude highly expressed: False

✅ Count Normalization Completed Successfully!
   ✓ Processed: 499,666 cells × 16,230 genes
   ✓ Runtime: 42.54s

🔍 Highly Variable Genes Selection:
   Method: seurat
   ⚠️ Gene indices [6460 7978] fell into a single bin: normalized dispersion set to 1
   💡 Consider decreasing `n_bins` to avoid this effect

✅ HVG Selection Completed Successfully!
   ✓ Selected: 1,135 highly variable genes out of 16,230 total (7.0%)
   ✓ Results added to AnnData object:
     • 'highly_variable': Boolean vector (adata.var)
     • 'means': Float vector (adata.var)
     • 'dispersions': Float vector (adata.var)
     • 'dispersions_norm': Float vector (adata.var)
   🔍 Simulating synthetic doublets...
   🔍 Normalizing observed and simulated data...

🔍 Count Normalization:
   Target sum: 1000000.0
   Exclude highly expressed: False

✅ Count Normalization Completed Successfully!
   ✓ Processed: 499,666 cells × 1,135 genes
   ✓ Runtime: 0.18s

🔍 Count Normalization:
   Target sum: 1000000.0
   Exclude highly expressed: False

✅ Count Normalization Completed Successfully!
   ✓ Processed: 999,332 cells × 1,135 genes
   ✓ Runtime: 1.60s
   🔍 Embedding transcriptomes using PCA...

Using CUDA device: NVIDIA GeForce RTX 3090
✅ Using built-in torch_pca for GPU-accelerated PCA
   🚀 Using torch_pca PCA for CUDA GPU acceleration in scrublet
   🚀 torch_pca PCA backend: CUDA GPU acceleration (scrublet, supports sparse)
   📊 Scrublet PCA input data type - X_obs: ndarray, shape: (499666, 1135), dtype: float64
   📊 Scrublet PCA input data type - X_sim: ndarray, shape: (999332, 1135), dtype: float64

╭─ SUMMARY: qc ──────────────────────────────────────────────────────╮
│  Duration: 702.244s                                                │
│  Shape:    1,384,942 x 16,248 (Unchanged)                          │
│                                                                    │
│  CHANGES DETECTED                                                  │
│  ────────────────                                                  │
╰────────────────────────────────────────────────────────────────────╯
```
---

## 💥 Error message
Exception
OutOfMemoryError
CUDA out of memory. Tried to allocate 4.23 GiB. GPU 0 has a total capacity of 23.69 GiB of which 1.79 GiB is free. Including non-PyTorch memory, this process has 21.88 GiB memory in use. Of the allocated memory 21.14 GiB is allocated by PyTorch, and 417.64 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation. See documentation for Memory Management (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)

**Comment by Starlitnightly** [comment]
#652

**Comment by Starlitnightly** [comment]
Hi @looon1, we have fixed this issue in latest version, could you try `pip install git+https://github.com/Starlitnightly/omicverse.git`

**Comment by amaukisumi** [comment]
I encountered a similar error when running `edgelist = scenic_obj.cal_grn(layer='counts')` , even though I had already updated to the latest version 2.1.3rc1 following the solution provided above. 
**torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 3.47 GiB. GPU 0 has a total capacity of 22.19 GiB of which 1.04 GiB is free. Including non-PyTorch memory, this process has 21.14 GiB memory in use. Of the allocated memory 19.29 GiB is allocated by PyTorch, and 1.55 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)**

**Comment by Starlitnightly** [comment]
Could you try to perform grn analysis on HVG?

**Comment by Starlitnightly** [comment]
> I encountered a similar error when running `edgelist = scenic_obj.cal_grn(layer='counts')` , even though I had already updated to the latest version 2.1.3rc1 following the solution provided above. **torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 3.47 GiB. GPU 0 has a total capacity of 22.19 GiB of which 1.04 GiB is free. Including non-PyTorch memory, this process has 21.14 GiB memory in use. Of the allocated memory 19.29 GiB is allocated by PyTorch, and 1.55 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation. See documentation for Memory Management (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)**

@amaukisumi Could you try to perform grn analysis on HVG?

**Comment by amaukisumi** [comment]
It works using just HVG. Thanks a lot!@Starlitnightly
